name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'  # Monthly

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Generate the build system
        run: cmake -B build

      - name: Build
        working-directory: build
        run: cmake --build .
